# 第十七章 错误处理与调试

## 错误处理

### try-catch语句

```js
try{
 // 可能会导致错误的代码
} catch(error){
  alert(error.message)
} finally {
  // 无论如何都会执行的语句
}
```

只要代码中包含finally 子句，那么无论try 还是catch 语句块中的return 语句都将被忽略。因此，在使用finally 子句之前，一定要非常清楚你想让代码怎么样。

### 抛出错误

```js
throw 12345
throw new Error("Something bad happened.")
throw new SyntaxError("I don’t like your syntax.")
throw new TypeError("What type of variable do you take me for?")
throw new RangeError("Sorry, you just don’t have the range.")
throw new EvalError("That doesn’t evaluate.")
throw new URIError("Uri, is that you?")
throw new ReferenceError("You didn’t cite your references properly.")
```
